#!/usr/bin/env python3
"""
HOG Configuration Transfer Utility for ESP32

This script transfers HOG configuration file generated by hog_processor from PC to ESP32.
Transfers <model_name>_hogcfg.json file to ESP32 filesystem.

Usage:
  python3 transfer_hog_config.py --model_name <model_name> --port <serial_port>

Example:
  python3 transfer_hog_config.py --model_name dataset_features --port /dev/ttyUSB0
  python3 transfer_hog_config.py -m dataset_features -p /dev/ttyUSB0
"""

import serial
import time
import os
import sys
import struct
import binascii
from pathlib import Path
import argparse

# Import configuration parser to sync with ESP32
try:
    from config_parser import get_user_chunk_size
except ImportError:
    print("⚠️  Warning: config_parser.py not found. Using default CHUNK_SIZE.")
    def get_user_chunk_size(config_file_path=None, default=220):
        return default

# --- Protocol Constants ---
# Must match the ESP32 receiver sketch
CMD_HEADER = b"ESP32_XFER"
CMD_START_SESSION = 0x01
CMD_FILE_INFO = 0x02
CMD_FILE_CHUNK = 0x03
CMD_END_SESSION = 0x04

RESP_ACK = b"ACK"
RESP_READY = b"READY"
RESP_OK = b"OK"
RESP_ERROR = b"ERROR"

# CHUNK_SIZE is now automatically extracted from Rf_board_config.h
CHUNK_SIZE = get_user_chunk_size(default=220)  # Auto-synced with Rf_board_config.h
CHUNK_DELAY = 0.03  # delay between chunks in seconds
MAX_RETRIES = 5     # max retries per chunk

# Timeout settings
SERIAL_TIMEOUT = 5  # seconds
ACK_TIMEOUT = 5    # seconds

def get_hog_config_file(model_name):
    """Get HOG config file from hog_transform/result directory for given model_name."""
    script_dir = os.path.dirname(__file__)
    # Go up: pc_side -> data_transfer -> hog_transform -> result
    hog_transform_dir = os.path.join(script_dir, '../..')
    hog_transform_dir = os.path.abspath(hog_transform_dir)
    result_dir = os.path.join(hog_transform_dir, 'result')
    
    # Look for <model_name>_hogcfg.json
    config_file = os.path.join(result_dir, f"{model_name}_hogcfg.json")
    
    if os.path.exists(config_file):
        return config_file
    
    # Fallback to hog_transform root directory for backward compatibility
    config_file_fallback = os.path.join(hog_transform_dir, f"{model_name}_hogcfg.json")
    if os.path.exists(config_file_fallback):
        print(f"⚠️  Found config in root directory. Consider moving to result/ folder.")
        return config_file_fallback
    
    return None

def _readline_with_timeout(ser, timeout_s=5.0):
    """Read a line with a soft timeout; returns stripped string (can be empty)."""
    end_time = time.time() + timeout_s
    line = b""
    while time.time() < end_time:
        part = ser.readline()
        if part:
            line = part
            break
        time.sleep(0.01)
    return line.decode(errors='ignore').strip()

def wait_for_response(ser, expected_response, timeout=ACK_TIMEOUT, verbose=True):
    """Wait for a specific response from the ESP32."""
    start_time = time.time()
    buffer = b""
    all_received = []  # Track all received data for debugging
    
    while time.time() - start_time < timeout:
        if ser.in_waiting > 0:
            new_data = ser.read(ser.in_waiting)
            buffer += new_data
            all_received.append(new_data)
            
            # Check if we have the expected response
            if expected_response in buffer:
                if verbose:
                    print(f"✅ Got response: {expected_response.decode()}")
                return True
                
            # Check for error response
            if b"ERROR" in buffer:
                if verbose:
                    print(f"❌ ESP32 reported ERROR: {buffer.decode(errors='ignore')}")
                return False
                
            # Clear buffer if it gets too large
            if len(buffer) > 1024:
                buffer = buffer[-512:]
                
        time.sleep(0.005)
        
    if verbose:
        # Show what we actually received for debugging
        all_data = b"".join(all_received).decode(errors='ignore')
        if all_data:
            print(f"❌ Timeout waiting for '{expected_response.decode()}'.")
            print(f"📥 Received from ESP32:\n{all_data}")
        else:
            print(f"❌ Timeout waiting for '{expected_response.decode()}'. No response from ESP32.")
    return False

def send_command(ser, command, payload=b""):
    """Send a command packet to the ESP32."""
    packet = CMD_HEADER + struct.pack('B', command) + payload
    ser.write(packet)
    ser.flush()
    time.sleep(0.01)

def transfer_file(ser, file_path, show_progress=True):
    """Transfer a single HOG config file to ESP32 with CRC verification."""
    if not os.path.exists(file_path):
        print(f"⚠️  Warning: File not found: {file_path}")
        return False

    file_size = os.path.getsize(file_path)
    filename = os.path.basename(file_path)
    
    if show_progress:
        print(f"\n🚀 Transferring {filename} ({file_size} bytes)")

    # Read the file data
    with open(file_path, 'rb') as f:
        file_data = f.read()
    
    # Compute full file CRC32
    file_crc = binascii.crc32(file_data) & 0xFFFFFFFF

    # 1. Send File Info with metadata (filename, size, CRC, chunk_size)
    filename_bytes = filename.encode('utf-8')
    payload = (struct.pack('B', len(filename_bytes)) + filename_bytes + 
               struct.pack('<III', file_size, file_crc, CHUNK_SIZE))
    send_command(ser, CMD_FILE_INFO, payload)

    if not wait_for_response(ser, RESP_ACK, verbose=show_progress):
        if show_progress:
            print("❌ ESP32 did not acknowledge file info.")
        return False

    # 2. Send File Chunks with per-chunk CRC and ACK/NACK
    bytes_sent = 0

    for offset in range(0, file_size, CHUNK_SIZE):
        chunk = file_data[offset:offset + CHUNK_SIZE]
        chunk_len = len(chunk)
        chunk_crc = binascii.crc32(chunk) & 0xFFFFFFFF
        header = struct.pack('<III', offset, chunk_len, chunk_crc)

        success = False
        for attempt in range(1, MAX_RETRIES + 1):
            # Send chunk with header
            send_command(ser, CMD_FILE_CHUNK, header + chunk)

            # Wait for ACK/NACK
            line = _readline_with_timeout(ser, timeout_s=5.0)
            if line.startswith("ACK "):
                try:
                    ack_off = int(line.split()[1])
                except Exception:
                    ack_off = -1
                if ack_off == offset:
                    success = True
                    break
            elif line.startswith("NACK "):
                if show_progress and line:
                    sys.stdout.write('\n')
                    print(f"   ↩ {line}")
                if attempt < MAX_RETRIES and show_progress:
                    print(f"⚠️  Retrying chunk at offset {offset} ({attempt}/{MAX_RETRIES})...")
                continue
            # Anything else: small delay and retry
            time.sleep(0.05)

        if not success:
            if show_progress:
                sys.stdout.write('\n')
                print(f"❌ Chunk transfer failed at offset {offset} after {MAX_RETRIES} retries")
            return False

        bytes_sent += chunk_len
        
        # Individual file progress bar
        if show_progress:
            progress = (bytes_sent / file_size) * 100
            bar_length = 40
            filled_len = int(bar_length * bytes_sent // file_size)
            bar = '█' * filled_len + '-' * (bar_length - filled_len)
            
            sys.stdout.write(f'   [{bar}] {progress:.1f}% complete\r')
            sys.stdout.flush()
        
        time.sleep(CHUNK_DELAY)

    if show_progress:
        sys.stdout.write('\n')
        print(f"✅ Finished transferring {filename}")
    return True

def check_config_file(model_name):
    """Check for HOG config file and print a report."""
    print("\n🔍 Searching for HOG config file...")
    config_file = get_hog_config_file(model_name)
    
    if not config_file:
        print(f"❌ No HOG config file found for model: {model_name}")
        print(f"   Expected file: {model_name}_hogcfg.json")
        print(f"   Make sure you've run hog_processor first to generate the config file.")
        return False
    
    size = os.path.getsize(config_file)
    print(f"📁 Found HOG config file:")
    print(f"   📋 {os.path.basename(config_file)} ({size} bytes)")
    
    # Show a preview of the config
    try:
        with open(config_file, 'r') as f:
            content = f.read(200)  # First 200 chars
            print(f"\n📄 Config preview:")
            print(f"   {content}...")
    except Exception as e:
        print(f"   ⚠️  Could not read file: {e}")
    
    return True

def main():
    parser = argparse.ArgumentParser(description="HOG Configuration Transfer Utility for ESP32")
    parser.add_argument('--model_name', '-m', required=True, help='Name of the model for HOG config')
    parser.add_argument('--port', '-p', required=True, help='Serial port for ESP32')
    args = parser.parse_args()

    model_name = args.model_name
    serial_port = args.port
    
    # Check for config file
    if not check_config_file(model_name):
        return 1
    
    config_file = get_hog_config_file(model_name)
    
    print(f"\n🔌 Connecting to ESP32 on {serial_port}...")
    try:
        ser = serial.Serial(serial_port, 115200, timeout=SERIAL_TIMEOUT)
        time.sleep(2)  # Allow ESP32 to reset
        print("✅ Connected!")
        
        # Clear any pending data and check for ESP32 startup messages
        time.sleep(0.5)
        if ser.in_waiting > 0:
            startup_data = ser.read(ser.in_waiting).decode(errors='ignore')
            print(f"📟 ESP32 startup messages:\n{startup_data}")
    except Exception as e:
        print(f"❌ Failed to connect: {e}")
        return 1

    try:
        # Start transfer session
        print("\n🚀 Starting HOG config transfer session...")
        session_name = model_name + "_hog_config"
        session_bytes = session_name.encode('utf-8')
        payload = struct.pack('B', len(session_bytes)) + session_bytes
        
        print(f"📤 Sending START_SESSION command with session name: {session_name}")
        send_command(ser, CMD_START_SESSION, payload)
        
        print("⏳ Waiting for ESP32 READY response...")
        if not wait_for_response(ser, RESP_READY):
            print("❌ ESP32 did not respond with READY.")
            print("\n💡 Troubleshooting tips:")
            print("   1. Make sure hog_config_receiver.ino is uploaded to the ESP32")
            print("   2. Press the RESET button on the ESP32 and try again")
            print("   3. Check that the ESP32 is not running a different program")
            print("   4. Open the Arduino Serial Monitor to see what the ESP32 is doing")
            return 1

        print("✅ ESP32 is ready to receive HOG config file.")

        # Transfer the config file
        if transfer_file(ser, config_file):
            print("✅ HOG config file transferred successfully!")
            
            # End session
            print("\n🏁 Ending transfer session...")
            send_command(ser, CMD_END_SESSION)
            
            if wait_for_response(ser, RESP_OK):
                print("✅ Transfer session completed successfully!")
                print("🎉 HOG configuration is now available on ESP32!")
                print(f"\n💡 In your ESP32 code, load the config with:")
                print(f"   hog.loadConfigFromFile(\"/{model_name}/{os.path.basename(config_file)}\");")
                return 0
            else:
                print("❌ ESP32 did not confirm session end.")
                return 1
        else:
            print("❌ Failed to transfer HOG config file.")
            return 1

    except KeyboardInterrupt:
        print("\n\n⚠️  Transfer interrupted by user.")
        return 1
    except Exception as e:
        print(f"\n❌ Transfer failed: {e}")
        import traceback
        traceback.print_exc()
        return 1
    finally:
        ser.close()

if __name__ == "__main__":
    exit(main())
